language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: react-tdd-clean
  cleanup: true
notifications:
  email: false
